### ISSUE TITLE
Setup using Self-managed Kubernetes is not working in Ubuntu 22.04

### ISSUE THREAD

**Issue by kanhaiya04** [kubearmor/KubeArmor#1083] opened 2023-02-01 21:41 UTC
## Bug Report

**General Information**

- OS:- Ubuntu 22.04

**To Reproduce**

1. Setup KubeArmor using Self-managed Kubernetes
2. Run `kubectl proxy &`
3. Run `$ cd KubeArmor/KubeArmor
~/KubeArmor/KubeArmor$ make run`

**Expected behavior**

KubeArmor should run directly in the host

**Screenshots**
![Screenshot from 2023-01-02 19-52-01](https://user-images.githubusercontent.com/93936630/216167010-c979716f-ca11-48ff-9cbf-764c581441ec.png)
![Screenshot from 2023-01-02 19-52-17](https://user-images.githubusercontent.com/93936630/216167112-a1186f2a-f428-479e-884c-f3284bda9bc3.png)

![Screenshot from 2023-01-02 19-52-21](https://user-images.githubusercontent.com/93936630/216166742-249baa66-80ed-4d36-8b4b-5eae4af53bc2.png)

**Comment by nyrahul** [comment] 2023-02-02 04:25
@PrimalPimmy, can you please check this issue? Can you setup the 22.04 VM and use the same instructions and check if there is any issue with 22.04?

**Comment by PrimalPimmy** [comment] 2023-02-02 04:26
Yes sure @nyrahul

**Comment by PrimalPimmy** [comment] 2023-02-02 05:18
@nyrahul @kanhaiya04 It's working for me fine using self managed k3s. What cluster type were you using?
![image](https://user-images.githubusercontent.com/23097199/216238137-b5a6966e-7d6b-48b1-b37d-51479fd3f797.png)

**Comment by Ankurk99** [comment] 2023-02-02 05:19
Hey @PrimalPimmy, it seems like you are using vagrant?

**Comment by PrimalPimmy** [comment] 2023-02-02 05:22
yes @Ankurk99

**Comment by Ankurk99** [comment] 2023-02-02 05:28
Is this the development vagrant we provide with KubeArmor or you setup one yourself and installed the Ubuntu image on it? 
The reason I asked is, we know that the vagrant setup is running fine (with updated bpftool version v5.5), but if someone tries it directly on their host (here it's Ubuntu 22.04) with k3s, then we are facing this issue.
If you are using our development vagrant, then can you please setup a separate demo Ubuntu 22.04 VM and check the whole thing there (after installing k3s in it)?

**Comment by PrimalPimmy** [comment] 2023-02-02 05:34
I set up a completely different vagrant setup @Ankurk99 . Not the demo. I had to manually install a few things to get it working. However it was not because of the error mentioned in this issue. bpftool was not there by default for me, so the one I installed is of version `5.15.30` that I got from linux-tools generic package
![image](https://user-images.githubusercontent.com/23097199/216240518-5a6e1149-a30d-4a61-8bf1-0a9d588a311c.png)

**Comment by Ankurk99** [comment] 2023-02-02 05:42
Ah! I see. Then it seems a bit tricky to actually replicate this.

**Comment by Ankurk99** [comment] 2023-02-02 06:28
We got it! 
If you do `kubectl get nodes -o wide` , you will see the hostname under `Name` . Now do `hostname` and the issue is that these two won't match if you are using different letter-casing in the hostname. So kubernetes lowers the casing and when you do `make run` it's unable to communicate with the host. 
The fix here would be to change the hostname to something in smallcase.
`hostnamectl set-hostname <smallcase-hostname>`

**Comment by rksharma95** [comment] 2023-02-28 05:23
@Ankurk99 can we close this issue?

**Closed as completed** 2023-02-28 05:26 UTC
Labels: bug
