### ISSUE TITLE
add support for amazon linux 2022 (AL2022)

### ISSUE THREAD

**Issue by yasin-cs-ko-ak** [kubearmor/KubeArmor#1079] opened 2023-01-30 03:36 UTC
## Feature Request

**Short Description**

KubeArmor could support amazon linux 2022.

**Is your feature request related to a problem? Please describe the use case.**

The OS is still in preview state and soon will be implemented across all aws services and it's good to have a support for that in the future.
Link: https://docs.aws.amazon.com/linux/al2022/ug/what-is-amazon-linux.html
Link: https://github.com/amazonlinux/amazon-linux-2022

**Describe the solution you'd like**

Create a support for amazon linux 2022.

**Comment by nyrahul** [comment] 2023-01-30 05:54
This is a duplicate of #1005.

**Closed as completed by nyrahul** 2023-01-30 05:54 UTC
Labels: enhancement
