### ISSUE TITLE
bug(alerts): Extra alert getting generated for some environments

### ISSUE THREAD

**Issue by DelusionalOptimist** [kubearmor/KubeArmor#1369] opened 2023-08-16 13:26 UTC
## Bug Report

**General Information**

- Environment description - K3s
- Kubearmor version - latest
- Kernel version (run `uname -a`) - `Linux kubearmor-dev-next 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use (e.g. `kubectl version`, ...) - 1.23.9+k3s1
- Link to relevant artifacts:
	Deployment - https://github.com/kubearmor/KubeArmor/blob/main/getting-started/deployment_guide.md#deploy-test-nginx-app
	Policy - https://github.com/kubearmor/KubeArmor/blob/main/getting-started/deployment_guide.md#deny-execution-of-package-management-tools-aptapt-get
- Target containers/pods - nginx

**To Reproduce**
1. Deploy Kubearmor, nginx and policy linked earlier.
2. Run `karmor logs`.
3. Run `kubectl exec -it deploy/nginx -- dash` and then generate a policy violation by running `apt`. You'll see an extra alert with PolicyName as DefaultPosture getting generated. Also note how the `ProcessName` are different for both.
	Alerts:
	```json
	{"Timestamp":1692190526,"UpdatedTime":"2023-08-16T12:55:26.285661Z","ClusterName":"default","HostName":"kubearmor-dev-next","NamespaceName":"default","Owner":{"Ref":"Deployment","Name":"nginx","Namespace":"default"},"PodName":"nginx-5c496f956c-8kxtq","Labels":"app=nginx","ContainerID":"8c2387de19d7ec7ce12ea4a21365ed33aec57309ef6557a00d52ea437af05e6c","ContainerName":"nginx","ContainerImage":"nginx:latest@sha256:13d22ec63300e16014d4a42aed735207a8b33c223cff19627dd3042e5a10a3a0","HostPPID":67958,"HostPID":69160,"PPID":47,"PID":54,"ParentProcessName":"/usr/bin/dash","ProcessName":"/usr/bin/apt","PolicyName":"block-pkg-mgmt-tools-exec","Severity":"1","Type":"MatchedPolicy","Source":"/usr/bin/dash","Operation":"Process","Resource":"/usr/bin/apt","Data":"syscall=SYS_EXECVE","Enforcer":"AppArmor","Action":"Block","Result":"Permission denied"}
	{"Timestamp":1692190526,"UpdatedTime":"2023-08-16T12:55:26.286001Z","ClusterName":"default","HostName":"kubearmor-dev-next","NamespaceName":"default","Owner":{"Ref":"Deployment","Name":"nginx","Namespace":"default"},"PodName":"nginx-5c496f956c-8kxtq","Labels":"app=nginx","ContainerID":"8c2387de19d7ec7ce12ea4a21365ed33aec57309ef6557a00d52ea437af05e6c","ContainerName":"nginx","ContainerImage":"nginx:latest@sha256:13d22ec63300e16014d4a42aed735207a8b33c223cff19627dd3042e5a10a3a0","HostPPID":67958,"HostPID":69160,"PPID":47,"PID":54,"ParentProcessName":"/usr/bin/dash","ProcessName":"/bin/apt","PolicyName":"DefaultPosture","Type":"MatchedPolicy","Source":"/usr/bin/dash","Operation":"Process","Resource":"/bin/apt","Data":"syscall=SYS_EXECVE","Enforcer":"AppArmor","Action":"Block","Result":"Permission denied"}
	```
	
	If the enforcer is BPFLSM the alerts generated have the same `policyName`.
	Alerts:
	```json
	{"Timestamp":1692192298,"UpdatedTime":"2023-08-16T13:24:58.447894Z","ClusterName":"default","HostName":"kubearmor-dev-next","NamespaceName":"default","Owner":{"Ref":"Deployment","Name":"nginx","Namespace":"default"},"PodName":"nginx-5c496f956c-8kxtq","Labels":"app=nginx","ContainerID":"8c2387de19d7ec7ce12ea4a21365ed33aec57309ef6557a00d52ea437af05e6c","ContainerName":"nginx","ContainerImage":"nginx:latest@sha256:13d22ec63300e16014d4a42aed735207a8b33c223cff19627dd3042e5a10a3a0","HostPPID":80303,"HostPID":96813,"PPID":93,"PID":105,"ParentProcessName":"/usr/bin/dash","ProcessName":"/usr/bin/apt","PolicyName":"block-pkg-mgmt-tools-exec","Severity":"1","Type":"MatchedPolicy","Source":"/usr/bin/dash","Operation":"Process","Resource":"/usr/bin/apt","Data":"syscall=SYS_EXECVE","Enforcer":"BPFLSM","Action":"Block","Result":"Permission denied"}
	{"Timestamp":1692192298,"UpdatedTime":"2023-08-16T13:24:58.448829Z","ClusterName":"default","HostName":"kubearmor-dev-next","NamespaceName":"default","Owner":{"Ref":"Deployment","Name":"nginx","Namespace":"default"},"PodName":"nginx-5c496f956c-8kxtq","Labels":"app=nginx","ContainerID":"8c2387de19d7ec7ce12ea4a21365ed33aec57309ef6557a00d52ea437af05e6c","ContainerName":"nginx","ContainerImage":"nginx:latest@sha256:13d22ec63300e16014d4a42aed735207a8b33c223cff19627dd3042e5a10a3a0","HostPPID":80303,"HostPID":96813,"PPID":93,"PID":105,"ParentProcessName":"/usr/bin/dash","ProcessName":"/usr/bin/apt","PolicyName":"block-pkg-mgmt-tools-exec","Severity":"1","Type":"MatchedPolicy","Source":"/usr/bin/dash","Operation":"Process","Resource":"/bin/apt","Data":"syscall=SYS_EXECVE","Enforcer":"BPFLSM","Action":"Block","Result":"Permission denied"}

	```

4. Now attach a bash shell using `kubectl exec -it deploy/nginx -- bash` and generate a policy violation by running `apt`. You'll see only a single alert is generated.

5. Deploy  [wordpress-mysql](https://github.com/kubearmor/KubeArmor/blob/main/examples/wordpress-mysql/wordpress-mysql-deployment.yaml) and try to replicate the scenario. Strangely, you'll see everything works as expected and you get a single alert for both dash and bash.

**Extra information**
Dash version:
Nginx pod - `Version: 0.5.12-2`
Wordpress pod - `Version: 0.5.7-4+b1`

Symlink info:
Nginx - `/bin -> /usr/bin`
Wordpress - no symlinks

**Expected behavior**

A single alert to be generated for all deployments.

**Update**
Checkout this [analysis](https://github.com/kubearmor/KubeArmor/wiki/Multiple-Alerts-Getting-Generated-For-A-Single-Deny-Action-When-Using-DASH) for understanding why this is happening.

**Comment by Shashankft9** [comment] 2023-08-17 03:45
some environment related details where I faced the issue for more clarity:
Environment description - K8s
Kubearmor version - latest
Kernel version (run uname -a) - `Linux k8s-master01 5.4.0-156-generic #173-Ubuntu SMP Tue Jul 11 07:25:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
Orchestration system version in use (e.g. kubectl version, ...) - 1.20

**Comment by DelusionalOptimist** [comment] 2023-08-25 10:37
@Shashankft9 Thank you for reporting this! I've documented what is happening in this [wiki](https://github.com/kubearmor/KubeArmor/wiki/Multiple-Alerts-Getting-Generated-For-A-Single-Deny-Action-When-Using-DASH) page. PTAL.

TL:DR 
This is not actually a bug but a feature. It happens due to DASH's internal logic for handling failure. KubeArmor is working as expected when it blocks both of them. : )

However, when using AppArmor the `DefaultPosture` logs are a problem but beyond our contorl. (Not the case with BPFLSM)
A possible workaround here could be using a policy which explicitly blocks the symlink dir.
```yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: block-pkg-mgmt-tools-exec
spec:
  selector:
    matchLabels:
      app: nginx
  process:
   matchPaths:
   - path: /usr/bin/apt
   matchDirectories:
   - dir: /bin/
  action:
    Block
```
@daemon1024 could there be any other better way to work around this?

**Comment by achrefbensaad** [comment] 2023-08-31 05:51
Closing this issue, as it is not a bug.

**Closed as completed by achrefbensaad** 2023-08-31 05:51 UTC
Labels: bug
