### ISSUE TITLE
KubeArmor policies not applied on OS:Ubuntu 22.04.2LTS 

### ISSUE THREAD

**Issue by hanshal101** [kubearmor/KubeArmor#1506] opened 2023-11-10 18:34 UTC
## Feature Request / Enhancement

**Short Description**

KubeArmor policies are not applied on pods.

**System Specifications**

OS : Ubuntu 22.04.2LTS
Kubernetes Cluster : Native/Docker
IDE : Lens IDE

**Steps to reproduce**

1. Prerequisites : Ubuntu 22.04.2LTS, Kubernetes and Docker
2. Install KubeArmor on the local cluster.
3. Create a nginx deployment as per the [Karmor-Docs](https://docs.kubearmor.io/kubearmor/quick-links/deployment_guide#deploy-test-nginx-app) and create the first security policy i.e `Deny execution of package management tools (apt/apt-get)`
4. Now simply follow the exec command and run `apt update` .

**Expected Output**
`sh: 1: apt: Permission denied
command terminated with exit code 126`

**My Output**
This command is updating the $POD. This is not the expected behaviour as I have Blocked all the actions on apt & apt-get for that pod.

**Some System information**

- lsm :  `cat /sys/kernel/security/lsm` ==> `lockdown,capability,landlock,yama,apparmor`
- Kernel Config : `cat /boot/config-6.2.0-36-generic > /home/lolcat/Karmor/kernelConfig.txt` ==> [kernelConfig.txt](https://github.com/kubearmor/KubeArmor/files/13322343/kernelConfig.txt)
- Kernel Version : `uname -r` ==> `6.2.0-36-generic`

**Karmor Commands**

- Karmor probe : 
![image](https://github.com/kubearmor/KubeArmor/assets/122217807/3efdfa5d-0fa1-4b5f-914e-7cd021ce5a74)

**Comment by rootxrishabh** [comment] 2024-02-13 22:24
@hanshal101  are you using an Apple chip machine? The Karmor probe output indicates a lack of Active LSM on the system. Based on the kernel version , it appears that LinuxKit is in use. LinuxKit is commonly used in Docker containers with apple chip, where support for LSMs is not available.

**Comment by hanshal101** [comment] 2024-02-14 20:47
Nope I am using Ubuntu-22.04 on a dual boot system with windows.

**Comment by rootxrishabh** [comment] 2024-02-15 00:04
Are you using docker desktop Kubernetes?

**Comment by hanshal101** [comment] 2024-02-15 13:54
Yes, using Docker Desktop for Kubernetes.

**Comment by rootxrishabh** [comment] 2024-02-15 14:00
I see!
Docker Desktop Kubernetes uses linuxkit to spin up vm for containers to enable kubernetes. The vm kernel doesn't have BPF-LSM or AppArmor and thus does not support kubearmor.
You need to use a kubearmor supported kubernetes distribution. You could check out kubearmor support matrix [here](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/support_matrix.md).

**Comment by hanshal101** [comment] 2024-02-15 14:24
Ohh
Well I see in the matrix page that Kubearmor is currently not supported in the Ubuntu:22.04 Version please guide me on this.

**Comment by rootxrishabh** [comment] 2024-02-15 15:17
It's not an issue with Ubuntu:22.04. `/sys/kernel/security/lsm` does show AppArmor enabled in your case which means it's an issue with your k8s distribution. I am using Ubuntu:22.04 with k3s and it works well. You can install k3s using this [script](https://github.com/kubearmor/KubeArmor/blob/main/contribution/k3s/install_k3s.sh).

**Comment by rootxrishabh** [comment] 2024-03-07 09:55
Closing this issue as I think the issue is addressed.

**Closed as completed by rootxrishabh** 2024-03-07 09:55 UTC
Labels: enhancement

**Comment by hanshal101** [comment] 2024-03-07 12:05
yup 👍
