### ISSUE TITLE
Failed test scenarios on Vagrant Env

### ISSUE THREAD

**Issue by nam-jaehyun** [kubearmor/KubeArmor#792] opened 2022-07-31 09:18 UTC
## Bug Report

**General Information**

- Environment description (GKE, VM-Kubeadm, vagrant-dev-env, minikube, microk8s, ...)
vagrant-dev-next + k3s (-> $ make vagrant-up NETNEXT=1)

- Kernel version (run `uname -a`)
Linux kernel 5.15

**To Reproduce**

vagrant-dev-next $ kubectl proxy &
vagrant-dev-next $ cd KubeArmor/tests

1. test-scenarios-github.sh

vagrant-dev-next $ ./test-scenarios-in-local.sh
(test scenarios failed)

2. test-scenarios-in-local.sh

vagrant-dev-next $ ./test-scenarios-in-local.sh
(test scenarios failed)

**Expected behavior**

All test scenarios should pass, but it seems that something is still missing in the bpf-lsm enforcer.

**Comment by nam-jaehyun** [comment] 2022-08-03 14:22
My testing env was wrong. KubeArmor works well.

**Comment by nam-jaehyun** [comment] 2022-08-03 14:24
I'm closing this issue.

**Comment by nam-jaehyun** [comment] 2022-08-03 14:24
My testing env was wrong. KubeArmor works well.

**Comment by daemon1024** [comment] 2022-08-07 17:51
I believe we can close this issue, since it's not reproducible anymore.
// @nam-jaehyun

**Closed as completed** 2022-08-23 14:19 UTC
Labels: bug
