### ISSUE TITLE
Fix readOnly policy match condition

### ISSUE THREAD

**Issue by oneiro-naut** [kubearmor/KubeArmor#352] opened 2021-09-15 07:05 UTC
## Bug Report
**General Information**

- Environment: vagrant-dev-env(kubearmor-dev-next)
- Kernel version: `Linux kubearmor-dev-next 5.13.0-14-generic #14-Ubuntu SMP Mon Aug 2 12:43:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use (e.g. `kubectl version`, ...)
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```
- Link to relevant artifacts (policies, deployments scripts, ...)
- Target containers/pods

**To Reproduce**

1. Apply a KubeArmorPolicy with action as `Audit` or `Allow` having `readOnly` for some file path. For example-
```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ubuntu-4-file-path-readonly-audit
  namespace: multiubuntu
spec:
  severity: 10
  message: "a critical file was accessed"
  tags:
  - WARNNING
  selector:
    matchLabels:
      container: ubuntu-4
  file:
    matchPaths:
    - path: /credentials/password # echo "test" >> /credentials/password (should get log, write op)
      readOnly: true # cat /credentials/password (should get no log, readOnly op)
  action:
    Audit
```
2. Perform read operation on that file using `cat <file_path>` command inside the corresponding pod. 
```
vagrant@kubearmor-dev-next:~$ kubectl exec -ti -n multiubuntu ubuntu-4-deployment-666b6dd9-mfmxl -- bash
root@ubuntu-4-deployment-666b6dd9-mfmxl:/# cat /credentials/password
password file
```
3. Check generated logs. There will be a MatchedPolicy log generated for the read operation just performed. Notice that there is a `O_RDONLY` flag in the log.
```
Policy","source":"/bin/cat /credentials/password","operation":"File","resource":"/credentials/password","data":"syscall=SYS_OPENAT fd=-100 flags=O_RDONLY","action":"Audit","result":"Passed"}
```
**Expected behavior**
We shouldn't get MatchedPolicy log for read operation when the event has O_RDONLY flag set.

**Comment by elfadel** [comment] 2021-10-01 11:25
Please, assign it to me.

**Comment by elfadel** [comment] 2021-10-03 10:36
> **Expected behavior**
> We shouldn't get MatchedPolicy log for read operation when the event has O_RDONLY flag set.

@oneiro-naut why?

**Comment by elfadel** [comment] 2021-10-04 11:31
The same question applied to #353 ...

**Comment by oneiro-naut** [comment] 2021-10-05 04:10
> @oneiro-naut why?

@elfadel Since the sample policy given above has `readOnly` set to true for `/credentials/password` file if the action were `Allow` or `Block` instead of `Audit` we won't see any log if some process tried to open the file to read(it will have O_RDONLY flag set) because our policy allows that. But if the process opened it to write(if it doesn't have O_RDONLY flag) it would get `Permission denied`. Here we want to audit only the write events because they are violations. The flags for syscall are stored in log struct field Data. https://github.com/kubearmor/KubeArmor/blob/44478fbce6dcf7248ae9ee01f51eace7080f88f3/KubeArmor/types/types.go#L216

**Comment by elfadel** [comment] 2021-10-05 18:11
@oneiro-naut thanks for your reply.
> Since the sample policy given above has `readOnly` set to true for `/credentials/password` file if the action were `Allow` or `Block` instead of `Audit` we won't see any log if some process tried to open the file to read(it will have O_RDONLY flag set) because our policy allows that.

Concerning `Block` and `Allow`, are you describing the expected or the actual behavior of KubeArmor?
Because, currently, when:
1. you set action to `Block`, the log is output for any operations: either read or write.
2. The same apply for `Allow` action (note that bash is not correctly started on pod ubuntu-4 when the action is set to `Allow` due to the way KubeArmor handles the [whitelist/blacklist](https://kubearmor.gitbook.io/kubearmor/getting-started/consideration_in_policy_action). Anyway, we can see that logs are output).

I think the expected behavior when `Audit` action and `readOnly` are associated is not clearly defined @nyrahul @nam-jaehyun.

My guess is that the fact that the log is output in the case @oneiro-naut describes here is not a bug, but the initial role intentionally assigned to log in this case. What am I missing?

**Comment by nam-jaehyun** [comment] 2021-10-07 11:24
@elfadel KubeArmor should not generate alerts for allowed operations.
However, as Ayush mentioned, we're getting the alert for allowed operations (O_RDONLY).
```
A log for an allowed operation != An alert
```
That is the key point of this issue.

**Closed as completed** 2021-10-21 06:24 UTC
Labels: bug
